**LIMPIEZA DE DATOS DE LECTURA DEL INVERSOR**
1. Determinar que datos son relevantes
2. Formatear correctamente

In [33]:
import pandas as pd
df = pd.read_csv('inverter_horario.csv')
df.head()

   inverterPower  productPower  onGridPower    fmtCollectTimeStr  powerProfit
0            0.0           0.0          0.0  2024-02-17 03:00:00          0.0
1            0.0           0.0          0.0  2024-02-17 04:00:00          0.0
2            0.0           0.0          0.0  2024-02-17 05:00:00          0.0
3            0.0           0.0          0.0  2024-02-17 06:00:00          0.0
4            0.0           0.0          0.0  2024-02-17 07:00:00          0.0

In [34]:
df.describe()

       inverterPower  productPower  onGridPower  powerProfit
count    8997.000000   8997.000000  8997.000000       8997.0
mean        0.337392      0.337392     0.007683          0.0
std         0.524752      0.524752     0.029420          0.0
min         0.000000      0.000000     0.000000          0.0
25%         0.000000      0.000000     0.000000          0.0
50%         0.020000      0.020000     0.000000          0.0
75%         0.480000      0.480000     0.000000          0.0
max         3.040000      3.040000     0.550000          0.0

In [35]:
df['inverterPower'] == df['productPower']

0       True
1       True
2       True
3       True
4       True
        ...
8992    True
8993    True
8994    True
8995    True
8996    True
Length: 8997, dtype: bool

### Descartamos las columnas powerProfit (por no existir datos relevantes) y productPower (por ser equivalente a inverterPower)

In [36]:
df_clean = df[['fmtCollectTimeStr', 'inverterPower']]
df_clean.head()

     fmtCollectTimeStr  inverterPower
0  2024-02-17 03:00:00            0.0
1  2024-02-17 04:00:00            0.0
2  2024-02-17 05:00:00            0.0
3  2024-02-17 06:00:00            0.0
4  2024-02-17 07:00:00            0.0

In [37]:
df_clean.loc[df_clean['fmtCollectTimeStr'] != None, 'date_time'] = df_clean['fmtCollectTimeStr'].astype(str).str[:20]
df_clean.loc[df_clean['fmtCollectTimeStr'] != None, 'date'] = df_clean['fmtCollectTimeStr'].astype(str).str[:10]
df_clean.loc[df_clean['fmtCollectTimeStr'] != None, 'time'] = df_clean['fmtCollectTimeStr'].astype(str).str[11:16]
df_clean.head()

/var/folders/nf/hsmn691n5xv9xhtsgqfd72vc0000gp/T/ipykernel_71007/1497944478.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.loc[df_clean['fmtCollectTimeStr'] != None, 'date_time'] = df_clean['fmtCollectTimeStr'].astype(str).str[:20]
/var/folders/nf/hsmn691n5xv9xhtsgqfd72vc0000gp/T/ipykernel_71007/1497944478.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.loc[df_clean['fmtCollectTimeStr'] != None, 'date'] = df_clean['fmtCollectTimeStr'].astype(str).str[:10]

     fmtCollectTimeStr  inverterPower            date_time        date   time
0  2024-02-17 03:00:00            0.0  2024-02-17 03:00:00  2024-02-17  03:00
1  2024-02-17 04:00:00            0.0  2024-02-17 04:00:00  2024-02-17  04:00
2  2024-02-17 05:00:00            0.0  2024-02-17 05:00:00  2024-02-17  05:00
3  2024-02-17 06:00:00            0.0  2024-02-17 06:00:00  2024-02-17  06:00
4  2024-02-17 07:00:00            0.0  2024-02-17 07:00:00  2024-02-17  07:00

In [38]:
# Obteniendo el día de la semana
df_clean.loc[df_clean['date_time'] != None, 'weekday'] = pd.to_datetime(df_clean['date_time'], format='mixed').dt.day_name()
df_clean.head()

,fmtCollectTimeStr,inverterPower,date_time,date,time,weekday
0,2024-02-17 03:00:00,0.0,2024-02-17 03:00:00,2024-02-17,03:00,Saturday
1,2024-02-17 04:00:00,0.0,2024-02-17 04:00:00,2024-02-17,04:00,Saturday
2,2024-02-17 05:00:00,0.0,2024-02-17 05:00:00,2024-02-17,05:00,Saturday
3,2024-02-17 06:00:00,0.0,2024-02-17 06:00:00,2024-02-17,06:00,Saturday
4,2024-02-17 07:00:00,0.0,2024-02-17 07:00:00,2024-02-17,07:00,Saturday

In [39]:
# Redondeando a dos decimales
df_clean['inverterPower'] = df_clean['inverterPower'].round(2)
df_clean.head()

,fmtCollectTimeStr,inverterPower,date_time,date,time,weekday
0,2024-02-17 03:00:00,0.0,2024-02-17 03:00:00,2024-02-17,03:00,Saturday
1,2024-02-17 04:00:00,0.0,2024-02-17 04:00:00,2024-02-17,04:00,Saturday
2,2024-02-17 05:00:00,0.0,2024-02-17 05:00:00,2024-02-17,05:00,Saturday
3,2024-02-17 06:00:00,0.0,2024-02-17 06:00:00,2024-02-17,06:00,Saturday
4,2024-02-17 07:00:00,0.0,2024-02-17 07:00:00,2024-02-17,07:00,Saturday

In [ ]:
# Nos quedamos con las columnas que nos interesan
df_clean_ok = df_clean[['date_time', 'date', 'time', 'weekday', 'inverterPower']]

In [41]:
df_clean_ok.to_csv('inverter_horario_clean.csv', index=False)