**ANALISIS CONSUMO ELECTRICO DE LA VIVIENDA**
1. Introducción
2. Definición objetivos
3. Indicadores
4. Importación de datos

# 1. Introducción
En los siguientes notebooks voy a analizar los datos de consumo elétrico recogidos por el inversor. Los datos que se han podido recoger de la web de huawei son desde el día 12 de agosto de 2023 y recogen lecturas cada 5 minutos.

# 2. Objetivo
El objetivo principal del presente estudio es describir el consumo durante los casi 2 años de datos. Concretamente nos interesa el comportamiento estacional del consumo, así como las anomalías en el mismo, de cara a tomar decisiones relatias a la modificación de la instalación, la revisión técnica o la reclamación de lecturas incorrectas por parte de la compañía eléctrica.

# 3. Indicadores
Los indicadores que nos intereses son:
- Consumo mínimo y máximo durante todo oel periodo para adapatar la potencia contratada
- Consumo mínimo y máximo diario
- Serie de consumo medio diario

# 4. Importación de datos
* La información importada del inversor se encuentra en el archivo "inverter_consumo.json"

In [14]:
import pandas as pd
df = pd.DataFrame(pd.read_json('inverter_consumos.json')['data'])
df.head(1)

                                                data
0  {'stationDn': 'NE=139361312', 'stationTimezone...

In [19]:
df_plain = pd.json_normalize(df['data'])
df_plain.head(1)

,stationDn,stationTimezone,clientTimezone,existInverter,existMeter,existEnergyStore,existCharge,existIrradiation,existUsePower,existDiesel,...,totalBuyPower,totalUsePower,selfProvide,totalGeneratorPower,onGridPowerRatio,selfUsePowerRatioByProduct,buyPowerRatio,selfUsePowerRatioByUse,generatorEnergyRatioByUse,xAxis
0,NE=139361312,NaN,NaN,True,True,False,False,False,NaN,NaN,...,11.36,25.46,14.10,--,1.61,98.39,44.62,55.38,--,"[2023-08-12 00:00 DST, 2023-08-12 00:05 DST, 2..."

In [23]:
df_target = df_plain[['productPower', 'usePower', 'selfUsePower', 'xAxis']]
df_target.head(2)

,productPower,usePower,selfUsePower,xAxis
0,"[0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.0...","[0.453, 0.456, 0.480, 0.509, 0.485, 0.653, 0.6...","[0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.0...","[2023-08-12 00:00 DST, 2023-08-12 00:05 DST, 2..."
1,"[0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.0...","[0.154, 0.314, 0.378, 0.469, 0.398, 0.401, 0.5...","[0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.0...","[2023-08-13 00:00 DST, 2023-08-13 00:05 DST, 2..."

In [25]:
df_exploded = df_target.apply(pd.Series.explode)
df_exploded.head(2)

  productPower usePower selfUsePower                 xAxis
0        0.000    0.453        0.000  2023-08-12 00:00 DST
0        0.000    0.456        0.000  2023-08-12 00:05 DST

In [32]:
df_exploded.dropna()
df_exploded.count()

productPower    180588
usePower        180588
selfUsePower    180588
xAxis           180588
dtype: int64

In [33]:
df_exploded.head(2)

  productPower usePower selfUsePower                 xAxis
0        0.000    0.453        0.000  2023-08-12 00:00 DST
0        0.000    0.456        0.000  2023-08-12 00:05 DST

In [34]:
df_exploded.to_csv('inverter_consumos.csv', index=False)