**RESUMEN FACTURACION AÑOS 2022 A 2025**

In [15]:
import pandas as pd
df = pd.read_json('consumos_facturados.json')
df.head()

,graficoConsumos,graficoImportes,resumenPorAnyo,comboAnyos,productosServicios,planGas,planEle,planDescripcion
0,"{'titulo': 'Consumo (kWh)', 'pie': ['07/12/202...","{'titulo': 'Importe de la factura (€)', 'pie':...","[{'anyo': 2021, 'importeTotal': 1004.19, 'impo...","[2025, 2024, 2023, 2022, 2021]",[],False,True,Tarifa regulada (PVPC)
1,"{'titulo': 'Consumo (kWh)', 'pie': ['10/12/202...","{'titulo': 'Importe de la factura (€)', 'pie':...","[{'anyo': 2022, 'importeTotal': 1212.08, 'impo...","[2025, 2024, 2023, 2022, 2021]",[],False,True,Tarifa regulada (PVPC)
2,"{'titulo': 'Consumo (kWh)', 'pie': ['12/12/202...","{'titulo': 'Importe de la factura (€)', 'pie':...","[{'anyo': 2023, 'importeTotal': 289.5, 'import...","[2025, 2024, 2023, 2022, 2021]",[],False,True,Tarifa regulada (PVPC)
3,"{'titulo': 'Consumo (kWh)', 'pie': ['11/12/202...","{'titulo': 'Importe de la factura (€)', 'pie':...","[{'anyo': 2024, 'importeTotal': 517.12, 'impor...","[2025, 2024, 2023, 2022, 2021]",[],False,True,Tarifa regulada (PVPC)
4,"{'titulo': 'Consumo (kWh)', 'pie': ['11/12/202...","{'titulo': 'Importe de la factura (€)', 'pie':...","[{'anyo': 2025, 'importeTotal': 279.01, 'impor...","[2025, 2024, 2023, 2022, 2021]",[],False,True,Tarifa regulada (PVPC)

In [16]:
df_graficoConsumos = pd.json_normalize(df['graficoConsumos'])
df_graficoConsumos.columns = ['graficoConsumos.' + col for col in df_graficoConsumos.columns]
df_graficoConsumos.head()

,graficoConsumos.titulo,graficoConsumos.pie,graficoConsumos.fecFactura,graficoConsumos.data,graficoConsumos.serieConsumo,graficoConsumos.peajeIva,graficoConsumos.showLegend,graficoConsumos.fecMinTerEne,graficoConsumos.fecMaxTerEne,graficoConsumos.numFactura,graficoConsumos.consumoTotal,graficoConsumos.labelPeriodo
0,Consumo (kWh),"[07/12/2020, 11/01/2021, 05/02/2021, 05/03/202...","[07/12/2020, 11/01/2021, 05/02/2021, 05/03/202...","[457.0, 802.0, 558.0, 415.0, 505.0, 338.0, 318...","[{'name': 'Sin discriminación horaria', 'legen...","[03201204030550559, 03210108030462106, 0321020...",None,None,None,None,None,Periodo del: 04/11/2020 al 06/12/2021
1,Consumo (kWh),"[10/12/2021, 18/01/2022, 08/02/2022, 08/03/202...","[10/12/2021, 18/01/2022, 08/02/2022, 08/03/202...","[622.0, 573.0, 405.0, 532.0, 586.0, 373.0, 478...","[{'name': 'Valle', 'legendIndex': 5, 'colorSin...","[03211207030456186, 03220114030503775, 0322020...",None,None,None,None,None,Periodo del: 04/11/2021 al 06/12/2022
2,Consumo (kWh),"[12/12/2022, 10/01/2023, 08/02/2023, 08/03/202...","[12/12/2022, 10/01/2023, 08/02/2023, 08/03/202...","[299.0, 388.0, 414.0, 293.0, 235.0, 202.0, 231...","[{'name': 'Valle', 'legendIndex': 5, 'colorSin...","[03221207030407965, 03230105030445581, 0323020...",None,None,None,None,None,Periodo del: 06/11/2022 al 04/12/2023
3,Consumo (kWh),"[11/12/2023, 09/01/2024, 09/02/2024, 11/03/202...","[11/12/2023, 09/01/2024, 09/02/2024, 11/03/202...","[364.0, 517.0, 519.0, 373.0, 364.0, 340.0, 384...","[{'name': 'Valle', 'legendIndex': 5, 'colorSin...","[03231205030483465, 03240105030437396, 0324020...",None,None,None,None,None,Periodo del: 06/11/2023 al 08/12/2024
4,Consumo (kWh),"[11/12/2024, 13/01/2025, 18/02/2025]","[11/12/2024, 13/01/2025, 18/02/2025]","[750.0, 685.0, 875.0]","[{'name': 'Valle', 'legendIndex': 5, 'colorSin...","[03241209030487802, 03250109030435353, 0325021...",None,None,None,None,None,Periodo del: 07/11/2024 al 11/02/2025

In [17]:
df_graficoImportes = pd.json_normalize(df['graficoImportes'])
df_graficoImportes.columns = ['graficoImportes.' + col for col in df_graficoImportes.columns]
df = pd.concat([df, df_graficoConsumos, df_graficoImportes], axis=1)
df.head()

,graficoConsumos,graficoImportes,resumenPorAnyo,comboAnyos,productosServicios,planGas,planEle,planDescripcion,graficoConsumos.titulo,graficoConsumos.pie,...,graficoImportes.fecMaxTer,graficoImportes.fecMinTer,graficoImportes.fecFactura,graficoImportes.estado,graficoImportes.numFactura,graficoImportes.importeFactura,graficoImportes.data,graficoImportes.labelPeriodo,graficoImportes.fecMax,graficoImportes.fecMin
0,"{'titulo': 'Consumo (kWh)', 'pie': ['07/12/202...","{'titulo': 'Importe de la factura (€)', 'pie':...","[{'anyo': 2021, 'importeTotal': 1004.19, 'impo...","[2025, 2024, 2023, 2022, 2021]",[],False,True,Tarifa regulada (PVPC),Consumo (kWh),"[07/12/2020, 11/01/2021, 05/02/2021, 05/03/202...",...,"[3 de diciembre de 2020, 7 de enero de 2021, 3...","[4 de noviembre de 2020, 3 de diciembre de 202...","[7 de diciembre de 2020, 11 de enero de 2021, ...",None,"[2020-12-07-22.49.04.698248, 2021-01-11-23.17....","[64.37, 104.07, 84.35, 52.28, 73.54, 61.49, 50...","[64.37, 104.07, 84.35, 52.28, 73.54, 61.49, 50...",Periodo del: 04/11/2020 al 06/12/2021,None,None
1,"{'titulo': 'Consumo (kWh)', 'pie': ['10/12/202...","{'titulo': 'Importe de la factura (€)', 'pie':...","[{'anyo': 2022, 'importeTotal': 1212.08, 'impo...","[2025, 2024, 2023, 2022, 2021]",[],False,True,Tarifa regulada (PVPC),Consumo (kWh),"[10/12/2021, 18/01/2022, 08/02/2022, 08/03/202...",...,"[6 de diciembre de 2021, 11 de enero de 2022, ...","[4 de noviembre de 2021, 6 de diciembre de 202...","[10 de diciembre de 2021, 18 de enero de 2022,...",None,"[2021-12-10-00.17.00.368565, 2022-01-17-23.48....","[126.84, 127.05, 94.2, 124.07, 167.9, 59.75, 8...","[126.84, 127.05, 94.2, 124.07, 167.9, 59.75, 8...",Periodo del: 04/11/2021 al 06/12/2022,None,None
2,"{'titulo': 'Consumo (kWh)', 'pie': ['12/12/202...","{'titulo': 'Importe de la factura (€)', 'pie':...","[{'anyo': 2023, 'importeTotal': 289.5, 'import...","[2025, 2024, 2023, 2022, 2021]",[],False,True,Tarifa regulada (PVPC),Consumo (kWh),"[12/12/2022, 10/01/2023, 08/02/2023, 08/03/202...",...,"[6 de diciembre de 2022, 4 de enero de 2023, 5...","[6 de noviembre de 2022, 6 de diciembre de 202...","[12 de diciembre de 2022, 10 de enero de 2023,...",None,"[2022-12-12-17.32.21.013999, 2023-01-10-18.48....","[31.63, 33.04, 29.39, 29.94, 20.38, 17.29, 18....","[31.63, 33.04, 29.39, 29.94, 20.38, 17.29, 18....",Periodo del: 06/11/2022 al 04/12/2023,None,None
3,"{'titulo': 'Consumo (kWh)', 'pie': ['11/12/202...","{'titulo': 'Importe de la factura (€)', 'pie':...","[{'anyo': 2024, 'importeTotal': 517.12, 'impor...","[2025, 2024, 2023, 2022, 2021]",[],False,True,Tarifa regulada (PVPC),Consumo (kWh),"[11/12/2023, 09/01/2024, 09/02/2024, 11/03/202...",...,"[4 de diciembre de 2023, 4 de enero de 2024, 6...","[6 de noviembre de 2023, 4 de diciembre de 202...","[11 de diciembre de 2023, 9 de enero de 2024, ...",None,"[2023-12-11-17.56.19.001579, 2024-01-09-17.58....","[26.67, 34.39, 39.15, 24.26, 23.11, 22.51, 27....","[26.67, 34.39, 39.15, 24.26, 23.11, 22.51, 27....",Periodo del: 06/11/2023 al 08/12/2024,None,None
4,"{'titulo': 'Consumo (kWh)', 'pie': ['11/12/202...","{'titulo': 'Importe de la factura (€)', 'pie':...","[{'anyo': 2025, 'importeTotal': 279.01, 'impor...","[2025, 2024, 2023, 2022, 2021]",[],False,True,Tarifa regulada (PVPC),Consumo (kWh),"[11/12/2024, 13/01/2025, 18/02/2025]",...,"[8 de diciembre de 2024, 8 de enero de 2025, 1...","[7 de noviembre de 2024, 8 de diciembre de 202...","[11 de diciembre de 2024, 13 de enero de 2025,...",None,"[2024-12-11-17.53.19.014521, 2025-01-13-17.49....","[114.57, 116.31, 162.7]","[114.57, 116.31, 162.7]",Periodo del: 07/11/2024 al 11/02/2025,None,None

In [18]:
df = df[[
  'graficoConsumos.pie',
  'graficoConsumos.fecFactura', 
  'graficoConsumos.data',
  'graficoConsumos.serieConsumo',
  'graficoImportes.pie',
  'graficoImportes.fecMaxTerEne', 
  'graficoImportes.fecMinTerEne',
  'graficoImportes.fecMinTerPot', 
  'graficoImportes.fecMaxTerPot',
  'graficoImportes.fecMaxTer', 
  'graficoImportes.fecMinTer',
  'graficoImportes.numFactura', 
  'graficoImportes.importeFactura',
  'graficoImportes.data', 
  ]]
df.head()

,graficoConsumos.pie,graficoConsumos.fecFactura,graficoConsumos.data,graficoConsumos.serieConsumo,graficoImportes.pie,graficoImportes.fecMaxTerEne,graficoImportes.fecMinTerEne,graficoImportes.fecMinTerPot,graficoImportes.fecMaxTerPot,graficoImportes.fecMaxTer,graficoImportes.fecMinTer,graficoImportes.numFactura,graficoImportes.importeFactura,graficoImportes.data
0,"[07/12/2020, 11/01/2021, 05/02/2021, 05/03/202...","[07/12/2020, 11/01/2021, 05/02/2021, 05/03/202...","[457.0, 802.0, 558.0, 415.0, 505.0, 338.0, 318...","[{'name': 'Sin discriminación horaria', 'legen...","[07/12/2020, 11/01/2021, 05/02/2021, 05/03/202...","[3 de diciembre de 2020, 7 de enero de 2021, 3...","[4 de noviembre de 2020, 3 de diciembre de 202...","[4 de noviembre de 2020, 3 de diciembre de 202...","[3 de diciembre de 2020, 7 de enero de 2021, 3...","[3 de diciembre de 2020, 7 de enero de 2021, 3...","[4 de noviembre de 2020, 3 de diciembre de 202...","[2020-12-07-22.49.04.698248, 2021-01-11-23.17....","[64.37, 104.07, 84.35, 52.28, 73.54, 61.49, 50...","[64.37, 104.07, 84.35, 52.28, 73.54, 61.49, 50..."
1,"[10/12/2021, 18/01/2022, 08/02/2022, 08/03/202...","[10/12/2021, 18/01/2022, 08/02/2022, 08/03/202...","[622.0, 573.0, 405.0, 532.0, 586.0, 373.0, 478...","[{'name': 'Valle', 'legendIndex': 5, 'colorSin...","[10/12/2021, 18/01/2022, 08/02/2022, 08/03/202...","[6 de diciembre de 2021, 11 de enero de 2022, ...","[4 de noviembre de 2021, 6 de diciembre de 202...","[4 de noviembre de 2021, 6 de diciembre de 202...","[6 de diciembre de 2021, 11 de enero de 2022, ...","[6 de diciembre de 2021, 11 de enero de 2022, ...","[4 de noviembre de 2021, 6 de diciembre de 202...","[2021-12-10-00.17.00.368565, 2022-01-17-23.48....","[126.84, 127.05, 94.2, 124.07, 167.9, 59.75, 8...","[126.84, 127.05, 94.2, 124.07, 167.9, 59.75, 8..."
2,"[12/12/2022, 10/01/2023, 08/02/2023, 08/03/202...","[12/12/2022, 10/01/2023, 08/02/2023, 08/03/202...","[299.0, 388.0, 414.0, 293.0, 235.0, 202.0, 231...","[{'name': 'Valle', 'legendIndex': 5, 'colorSin...","[12/12/2022, 10/01/2023, 08/02/2023, 08/03/202...","[6 de diciembre de 2022, 4 de enero de 2023, 5...","[6 de noviembre de 2022, 6 de diciembre de 202...","[6 de noviembre de 2022, 6 de diciembre de 202...","[6 de diciembre de 2022, 4 de enero de 2023, 5...","[6 de diciembre de 2022, 4 de enero de 2023, 5...","[6 de noviembre de 2022, 6 de diciembre de 202...","[2022-12-12-17.32.21.013999, 2023-01-10-18.48....","[31.63, 33.04, 29.39, 29.94, 20.38, 17.29, 18....","[31.63, 33.04, 29.39, 29.94, 20.38, 17.29, 18...."
3,"[11/12/2023, 09/01/2024, 09/02/2024, 11/03/202...","[11/12/2023, 09/01/2024, 09/02/2024, 11/03/202...","[364.0, 517.0, 519.0, 373.0, 364.0, 340.0, 384...","[{'name': 'Valle', 'legendIndex': 5, 'colorSin...","[11/12/2023, 09/01/2024, 09/02/2024, 11/03/202...","[4 de diciembre de 2023, 4 de enero de 2024, 6...","[6 de noviembre de 2023, 4 de diciembre de 202...","[6 de noviembre de 2023, 4 de diciembre de 202...","[4 de diciembre de 2023, 4 de enero de 2024, 6...","[4 de diciembre de 2023, 4 de enero de 2024, 6...","[6 de noviembre de 2023, 4 de diciembre de 202...","[2023-12-11-17.56.19.001579, 2024-01-09-17.58....","[26.67, 34.39, 39.15, 24.26, 23.11, 22.51, 27....","[26.67, 34.39, 39.15, 24.26, 23.11, 22.51, 27...."
4,"[11/12/2024, 13/01/2025, 18/02/2025]","[11/12/2024, 13/01/2025, 18/02/2025]","[750.0, 685.0, 875.0]","[{'name': 'Valle', 'legendIndex': 5, 'colorSin...","[11/12/2024, 13/01/2025, 18/02/2025]","[8 de diciembre de 2024, 8 de enero de 2025, 1...","[7 de noviembre de 2024, 8 de diciembre de 202...","[7 de noviembre de 2024, 8 de diciembre de 202...","[8 de diciembre de 2024, 8 de enero de 2025, 1...","[8 de diciembre de 2024, 8 de enero de 2025, 1...","[7 de noviembre de 2024, 8 de diciembre de 202...","[2024-12-11-17.53.19.014521, 2025-01-13-17.49....","[114.57, 116.31, 162.7]","[114.57, 116.31, 162.7]"

In [19]:
df_serieConsumo = pd.json_normalize(df['graficoConsumos.serieConsumo'])
df_serieConsumo.head()

,0,1,2,3
0,"{'name': 'Sin discriminación horaria', 'legend...","{'name': 'Valle', 'legendIndex': 5, 'colorSinC...","{'name': 'Llano', 'legendIndex': 4, 'colorSinC...","{'name': 'Punta', 'legendIndex': 3, 'colorSinC..."
1,"{'name': 'Valle', 'legendIndex': 5, 'colorSinC...","{'name': 'Llano', 'legendIndex': 4, 'colorSinC...","{'name': 'Punta', 'legendIndex': 3, 'colorSinC...",None
2,"{'name': 'Valle', 'legendIndex': 5, 'colorSinC...","{'name': 'Llano', 'legendIndex': 4, 'colorSinC...","{'name': 'Punta', 'legendIndex': 3, 'colorSinC...",None
3,"{'name': 'Valle', 'legendIndex': 5, 'colorSinC...","{'name': 'Llano', 'legendIndex': 4, 'colorSinC...","{'name': 'Punta', 'legendIndex': 3, 'colorSinC...",None
4,"{'name': 'Valle', 'legendIndex': 5, 'colorSinC...","{'name': 'Llano', 'legendIndex': 4, 'colorSinC...","{'name': 'Punta', 'legendIndex': 3, 'colorSinC...",None

In [20]:
df = df.drop(columns=['graficoConsumos.serieConsumo'])
df.head()

,graficoConsumos.pie,graficoConsumos.fecFactura,graficoConsumos.data,graficoImportes.pie,graficoImportes.fecMaxTerEne,graficoImportes.fecMinTerEne,graficoImportes.fecMinTerPot,graficoImportes.fecMaxTerPot,graficoImportes.fecMaxTer,graficoImportes.fecMinTer,graficoImportes.numFactura,graficoImportes.importeFactura,graficoImportes.data
0,"[07/12/2020, 11/01/2021, 05/02/2021, 05/03/202...","[07/12/2020, 11/01/2021, 05/02/2021, 05/03/202...","[457.0, 802.0, 558.0, 415.0, 505.0, 338.0, 318...","[07/12/2020, 11/01/2021, 05/02/2021, 05/03/202...","[3 de diciembre de 2020, 7 de enero de 2021, 3...","[4 de noviembre de 2020, 3 de diciembre de 202...","[4 de noviembre de 2020, 3 de diciembre de 202...","[3 de diciembre de 2020, 7 de enero de 2021, 3...","[3 de diciembre de 2020, 7 de enero de 2021, 3...","[4 de noviembre de 2020, 3 de diciembre de 202...","[2020-12-07-22.49.04.698248, 2021-01-11-23.17....","[64.37, 104.07, 84.35, 52.28, 73.54, 61.49, 50...","[64.37, 104.07, 84.35, 52.28, 73.54, 61.49, 50..."
1,"[10/12/2021, 18/01/2022, 08/02/2022, 08/03/202...","[10/12/2021, 18/01/2022, 08/02/2022, 08/03/202...","[622.0, 573.0, 405.0, 532.0, 586.0, 373.0, 478...","[10/12/2021, 18/01/2022, 08/02/2022, 08/03/202...","[6 de diciembre de 2021, 11 de enero de 2022, ...","[4 de noviembre de 2021, 6 de diciembre de 202...","[4 de noviembre de 2021, 6 de diciembre de 202...","[6 de diciembre de 2021, 11 de enero de 2022, ...","[6 de diciembre de 2021, 11 de enero de 2022, ...","[4 de noviembre de 2021, 6 de diciembre de 202...","[2021-12-10-00.17.00.368565, 2022-01-17-23.48....","[126.84, 127.05, 94.2, 124.07, 167.9, 59.75, 8...","[126.84, 127.05, 94.2, 124.07, 167.9, 59.75, 8..."
2,"[12/12/2022, 10/01/2023, 08/02/2023, 08/03/202...","[12/12/2022, 10/01/2023, 08/02/2023, 08/03/202...","[299.0, 388.0, 414.0, 293.0, 235.0, 202.0, 231...","[12/12/2022, 10/01/2023, 08/02/2023, 08/03/202...","[6 de diciembre de 2022, 4 de enero de 2023, 5...","[6 de noviembre de 2022, 6 de diciembre de 202...","[6 de noviembre de 2022, 6 de diciembre de 202...","[6 de diciembre de 2022, 4 de enero de 2023, 5...","[6 de diciembre de 2022, 4 de enero de 2023, 5...","[6 de noviembre de 2022, 6 de diciembre de 202...","[2022-12-12-17.32.21.013999, 2023-01-10-18.48....","[31.63, 33.04, 29.39, 29.94, 20.38, 17.29, 18....","[31.63, 33.04, 29.39, 29.94, 20.38, 17.29, 18...."
3,"[11/12/2023, 09/01/2024, 09/02/2024, 11/03/202...","[11/12/2023, 09/01/2024, 09/02/2024, 11/03/202...","[364.0, 517.0, 519.0, 373.0, 364.0, 340.0, 384...","[11/12/2023, 09/01/2024, 09/02/2024, 11/03/202...","[4 de diciembre de 2023, 4 de enero de 2024, 6...","[6 de noviembre de 2023, 4 de diciembre de 202...","[6 de noviembre de 2023, 4 de diciembre de 202...","[4 de diciembre de 2023, 4 de enero de 2024, 6...","[4 de diciembre de 2023, 4 de enero de 2024, 6...","[6 de noviembre de 2023, 4 de diciembre de 202...","[2023-12-11-17.56.19.001579, 2024-01-09-17.58....","[26.67, 34.39, 39.15, 24.26, 23.11, 22.51, 27....","[26.67, 34.39, 39.15, 24.26, 23.11, 22.51, 27...."
4,"[11/12/2024, 13/01/2025, 18/02/2025]","[11/12/2024, 13/01/2025, 18/02/2025]","[750.0, 685.0, 875.0]","[11/12/2024, 13/01/2025, 18/02/2025]","[8 de diciembre de 2024, 8 de enero de 2025, 1...","[7 de noviembre de 2024, 8 de diciembre de 202...","[7 de noviembre de 2024, 8 de diciembre de 202...","[8 de diciembre de 2024, 8 de enero de 2025, 1...","[8 de diciembre de 2024, 8 de enero de 2025, 1...","[7 de noviembre de 2024, 8 de diciembre de 202...","[2024-12-11-17.53.19.014521, 2025-01-13-17.49....","[114.57, 116.31, 162.7]","[114.57, 116.31, 162.7]"

In [21]:
df.columns

Index(['graficoConsumos.pie', 'graficoConsumos.fecFactura',
       'graficoConsumos.data', 'graficoImportes.pie',
       'graficoImportes.fecMaxTerEne', 'graficoImportes.fecMinTerEne',
       'graficoImportes.fecMinTerPot', 'graficoImportes.fecMaxTerPot',
       'graficoImportes.fecMaxTer', 'graficoImportes.fecMinTer',
       'graficoImportes.numFactura', 'graficoImportes.importeFactura',
       'graficoImportes.data'],
      dtype='object')

In [22]:
series_dict = {col: df[col].explode().reset_index(drop=True) for col in df.columns}
series_dict['graficoConsumos.pie']

0     07/12/2020
1     11/01/2021
2     05/02/2021
3     05/03/2021
4     09/04/2021
5     07/05/2021
6     09/07/2021
7     09/07/2021
8     09/08/2021
9     08/09/2021
10    08/10/2021
11    16/11/2021
12    10/12/2021
13    10/12/2021
14    18/01/2022
15    08/02/2022
16    08/03/2022
17    08/04/2022
18    09/05/2022
19    08/06/2022
20    08/07/2022
21    08/08/2022
22    08/09/2022
23    10/10/2022
24    09/11/2022
25    12/12/2022
26    12/12/2022
27    10/01/2023
28    08/02/2023
29    08/03/2023
30    11/04/2023
31    09/05/2023
32    08/06/2023
33    10/07/2023
34    08/08/2023
35    08/09/2023
36    09/10/2023
37    09/11/2023
38    11/12/2023
39    11/12/2023
40    09/01/2024
41    09/02/2024
42    11/03/2024
43    09/04/2024
44    10/05/2024
45    11/06/2024
46    09/07/2024
47    09/08/2024
48    10/09/2024
49    09/10/2024
50    12/11/2024
51    11/12/2024
52    11/12/2024
53    13/01/2025
54    18/02/2025
Name: graficoConsumos.pie, dtype: object

In [23]:
df_clean = pd.DataFrame(series_dict)
df_clean.head()

,graficoConsumos.pie,graficoConsumos.fecFactura,graficoConsumos.data,graficoImportes.pie,graficoImportes.fecMaxTerEne,graficoImportes.fecMinTerEne,graficoImportes.fecMinTerPot,graficoImportes.fecMaxTerPot,graficoImportes.fecMaxTer,graficoImportes.fecMinTer,graficoImportes.numFactura,graficoImportes.importeFactura,graficoImportes.data
0,07/12/2020,07/12/2020,457.0,07/12/2020,3 de diciembre de 2020,4 de noviembre de 2020,4 de noviembre de 2020,3 de diciembre de 2020,3 de diciembre de 2020,4 de noviembre de 2020,2020-12-07-22.49.04.698248,64.37,64.37
1,11/01/2021,11/01/2021,802.0,11/01/2021,7 de enero de 2021,3 de diciembre de 2020,3 de diciembre de 2020,7 de enero de 2021,7 de enero de 2021,3 de diciembre de 2020,2021-01-11-23.17.35.604889,104.07,104.07
2,05/02/2021,05/02/2021,558.0,05/02/2021,3 de febrero de 2021,7 de enero de 2021,7 de enero de 2021,3 de febrero de 2021,3 de febrero de 2021,7 de enero de 2021,2021-02-05-23.08.35.928849,84.35,84.35
3,05/03/2021,05/03/2021,415.0,05/03/2021,3 de marzo de 2021,3 de febrero de 2021,3 de febrero de 2021,3 de marzo de 2021,3 de marzo de 2021,3 de febrero de 2021,2021-03-05-22.59.33.768713,52.28,52.28
4,09/04/2021,09/04/2021,505.0,09/04/2021,7 de abril de 2021,3 de marzo de 2021,3 de marzo de 2021,7 de abril de 2021,7 de abril de 2021,3 de marzo de 2021,2021-04-09-23.28.34.470604,73.54,73.54

In [24]:
df_clean = df_clean.drop_duplicates()
df_clean.count()

graficoConsumos.pie               51
graficoConsumos.fecFactura        51
graficoConsumos.data              51
graficoImportes.pie               51
graficoImportes.fecMaxTerEne      51
graficoImportes.fecMinTerEne      51
graficoImportes.fecMinTerPot      51
graficoImportes.fecMaxTerPot      51
graficoImportes.fecMaxTer         51
graficoImportes.fecMinTer         51
graficoImportes.numFactura        51
graficoImportes.importeFactura    51
graficoImportes.data              51
dtype: int64

In [25]:
df_clean['graficoConsumos.anno_mes'] = pd.to_datetime(df_clean['graficoConsumos.pie'], format='%d/%m/%Y').dt.strftime('%y-%m')

In [26]:
# Renombra las columnas
df_clean.rename(columns={
  'graficoConsumos.anno_mes': 'Año-mes',
  'graficoConsumos.pie': 'Fecha consumo',
  'graficoConsumos.fecFactura': 'Fecha Factura',
  'graficoConsumos.data': 'Consumo',
  'graficoImportes.pie': 'Fecha Facturación',
  'graficoImportes.fecMaxTerEne': 'Fecha Maxima Término Energia',
  'graficoImportes.fecMinTerEne': 'Fecha Minima Término Energia',
  'graficoImportes.fecMinTerPot': 'Fecha Minima Término Potencia',
  'graficoImportes.fecMaxTerPot': 'Fecha Maxima Término Potencia',
  'graficoImportes.fecMaxTer': 'Fecha Máxima Término',
  'graficoImportes.fecMinTer': 'Fecha Minima Término',
  'graficoImportes.numFactura': 'Numero Factura',
  'graficoImportes.importeFactura': 'Importe Factura',
  'graficoImportes.data': 'Importe',
}, inplace=True)

In [27]:
# Ajustar formato de las fechas yyyy-mm-dd
import locale
locale.setlocale(locale.LC_TIME, 'es_ES.UTF-8')
df_clean['Fecha consumo'] = pd.to_datetime(df_clean['Fecha consumo'], format='%d/%m/%Y').dt.strftime('%Y-%m-%d')
df_clean['Fecha Factura'] = pd.to_datetime(df_clean['Fecha Factura'], format='%d/%m/%Y').dt.strftime('%Y-%m-%d')
df_clean['Fecha Facturación'] = pd.to_datetime(df_clean['Fecha Facturación'], format='%d/%m/%Y').dt.strftime('%Y-%m-%d')
df_clean['Fecha Maxima Término Energia'] = pd.to_datetime(df_clean['Fecha Maxima Término Energia'], format='%d de %B de %Y').dt.strftime('%Y-%m-%d')
df_clean['Fecha Minima Término Energia'] = pd.to_datetime(df_clean['Fecha Minima Término Energia'], format='%d de %B de %Y').dt.strftime('%Y-%m-%d')
df_clean['Fecha Minima Término Potencia'] = pd.to_datetime(df_clean['Fecha Minima Término Potencia'], format='%d de %B de %Y').dt.strftime('%Y-%m-%d')
df_clean['Fecha Maxima Término Potencia'] = pd.to_datetime(df_clean['Fecha Maxima Término Potencia'], format='%d de %B de %Y').dt.strftime('%Y-%m-%d')
df_clean['Fecha Máxima Término'] = pd.to_datetime(df_clean['Fecha Máxima Término'], format='%d de %B de %Y').dt.strftime('%Y-%m-%d')
df_clean['Fecha Minima Término'] = pd.to_datetime(df_clean['Fecha Minima Término'], format='%d de %B de %Y').dt.strftime('%Y-%m-%d')

In [28]:
df_clean.to_csv('consumos_facturados_clean.csv', index=False)